<?php

use Chess\Figure\Bishop;
use Chess\Figure\King;
use Chess\Figure\Knight;
use Chess\Figure\Pawn;
use Chess\Figure\Queen;
use Chess\Figure\Rook;
use Chess\Game;
use Chess\Player;
use PHPUnit\Framework\TestCase;

class FigurePawnTest extends TestCase
{
    /** @var Game  */
    protected $game = null;
    /** @var Player  */
    protected $player = null;
    /** @var Player  */
    protected $enemyPlayer = null;
    /** @var Knight  */
    protected $figure = null;
    /** @var King */
    protected $allyKing = null;
    /** @var King */
    protected $enemyKing = null;
    /** @var Queen */
    protected $enemyQueen = null;
    /** @var Bishop */
    protected $enemyBishop = null;

    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->game = new Game();
        $this->game->init();

        $this->player = $this->game->addPlayer('test1');
        $this->figure = new Pawn($this->player, 4, 6);
        $this->allyKing = new King($this->player, 3, 6);

        $this->player->createFigures([
            $this->figure,
            $this->allyKing
        ]);

        $this->enemyPlayer = $this->game->addPlayer('test2');
        $this->enemyQueen = new Queen($this->enemyPlayer, 3, 2);
        $this->enemyBishop = new Rook($this->enemyPlayer, 7, 2);
        $this->enemyKing = new King($this->enemyPlayer, 5, 5);

        $this->enemyPlayer->createFigures([
            $this->enemyQueen,
            $this->enemyBishop,
            $this->enemyKing
        ]);

        $this->game->start();

    }

    function testVerify() {
        $enemies = $this->enemyPlayer->getFigures();
        $allies = $this->player->getFigures();

        for ($x = 0; $x < 8; $x++) {
            for($y = 0; $y < 8; $y++) {
                if(
                    ($x == 4 && $y == 4)
                    || ($x == 4 && $y == 5)
                    || ($x == 5 && $y == 5)
                ) {
                    $this->assertTrue($this->figure->verify($x, $y, $allies, $enemies));
                } else {
                    $this->assertFalse($this->figure->verify($x, $y, $allies, $enemies));
                }
            }
        }
    }

    function testCanSave()
    {
        $this->player->check($this->enemyBishop->getId());
        $this->assertTrue($this->figure->canSave($this->allyKing, $this->enemyBishop,$this->player->getFigures(), $this->enemyPlayer->getFigures()));
        $this->player->check(null);
        $this->player->check($this->enemyQueen->getId());
        $this->assertFalse($this->figure->canSave($this->allyKing, $this->enemyQueen, $this->player->getFigures(), $this->enemyPlayer->getFigures()));
    }

    function testAttackKing()
    {
        $this->assertTrue($this->figure->attackKing($this->enemyKing, $this->player->getFigures(), $this->enemyPlayer->getFigures()));
        $this->enemyKing->move(6, 5, $this->enemyPlayer->getFigures(), $this->player->getFigures());

        $this->assertFalse($this->figure->attackKing($this->enemyKing, $this->player->getFigures(), $this->enemyPlayer->getFigures()));
    }

    function tearDown()
    {
        $this->game->delete();
    }


}
