<?php


use Chess\Figure\Bishop;
use Chess\Figure\King;
use Chess\Figure\Knight;
use Chess\Figure\Pawn;
use Chess\Figure\Queen;
use Chess\Figure\Rook;
use Chess\Game;
use Chess\Player;
use PHPUnit\Framework\TestCase;

class FigureBishopTest extends TestCase
{
    /** @var Game  */
    protected $game = null;
    /** @var Player  */
    protected $player = null;
    /** @var Player  */
    protected $enemyPlayer = null;
    /** @var Bishop  */
    protected $figure = null;
    /** @var Bishop  */
    protected $figure1 = null;
    /** @var King */
    protected $allyKing = null;
    /** @var King */
    protected $enemyKing = null;
    /** @var Queen */
    protected $enemyQueen = null;

    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->game = new Game();
        $this->game->init();

        $this->player = $this->game->addPlayer('test1');
        $this->figure = new Bishop($this->player, 6, 4);
        $this->figure1 = new Bishop($this->player, 7, 5);
        $this->allyKing = new King($this->player, 5, 7);

        $this->player->createFigures([
            $this->figure,
            $this->figure1,
            $this->allyKing
        ]);

        $this->enemyPlayer = $this->game->addPlayer('test2');
        $this->enemyKing = new King($this->enemyPlayer, 2, 0);
        $this->enemyQueen = new Queen($this->enemyPlayer, 1, 3);

        $this->enemyPlayer->createFigures([
            $this->enemyKing,
            $this->enemyQueen
        ]);

        $this->game->start();

    }


    function testVerify() {
        $enemies = $this->enemyPlayer->getFigures();
        $allies = $this->player->getFigures();

        for ($x = 7; $x >= 0; $x--) {
            for($y = 7; $y >= 0; $y--) {
                if(
                    ($x == 2 && $y == 0)
                    || ($x == 3 && $y == 1)
                    || ($x == 4 && $y == 2)
                    || ($x == 5 && $y == 3)
                    || ($x == 7 && $y == 3)
                    || ($x == 5 && $y == 5)
                    || ($x == 6 && $y == 4)
                    || ($x == 4 && $y == 6)
                    || ($x == 3 && $y == 7)
                ) {
                    $this->assertTrue($this->figure->verify($x, $y, $allies, $enemies), "true $x $y");
                } else {
                    $this->assertFalse($this->figure->verify($x, $y, $allies, $enemies), "false $x $y");
                }
            }
        }
    }

    function testCanSave()
    {
        $this->player->check($this->enemyQueen->getId());
        $this->assertTrue($this->figure->canSave($this->allyKing, $this->enemyQueen, $this->player->getFigures(), $this->enemyPlayer->getFigures()));
        $this->assertFalse($this->figure1->canSave($this->allyKing, $this->enemyQueen, $this->player->getFigures(), $this->enemyPlayer->getFigures()));
    }

    function testAttackKing()
    {
        $allies = $this->player->getFigures();
        $enemies = $this->enemyPlayer->getFigures();
        $this->assertTrue($this->figure->attackKing($this->enemyKing, $allies,  $enemies));

        $this->enemyKing->move(2, 1, $enemies, $allies);
        $this->assertFalse($this->figure->attackKing($this->enemyKing, $allies,  $enemies));
    }

    function tearDown()
    {
        $this->game->delete();
    }
}
