<?php


use Chess\Figure\Bishop;
use Chess\Figure\King;
use Chess\Figure\Knight;
use Chess\Figure\Pawn;
use Chess\Figure\Queen;
use Chess\Figure\Rook;
use Chess\Game;
use Chess\Player;
use PHPUnit\Framework\TestCase;

class FigureQueenTest extends TestCase
{
    /** @var Game  */
    protected $game = null;
    /** @var Player  */
    protected $player = null;
    /** @var Player  */
    protected $enemyPlayer = null;
    /** @var Queen  */
    protected $figure = null;
    /** @var King */
    protected $allyKing = null;
    /** @var Pawn */
    protected $allyPawn = null;
    /** @var Pawn */
    protected $testPawn = null;
    /** @var King */
    protected $enemyKing = null;
    /** @var Rook */
    protected $enemyBishop = null;

    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->game = new Game();
        $this->game->init();

        $this->player = $this->game->addPlayer('test1');
        $this->figure = new Queen($this->player, 3, 2);
        $this->allyKing = new King($this->player, 5, 1);
        $this->allyPawn = new Pawn($this->player, 6, 2);
        $this->testPawn = new Pawn($this->player, 6, 5);

        $this->player->createFigures([
            $this->figure,
            $this->allyKing,
            $this->allyPawn,
            $this->testPawn
        ]);

        $this->enemyPlayer = $this->game->addPlayer('test2');
        $this->enemyKing = new King($this->enemyPlayer, 3, 7);
        $this->enemyBishop = new Bishop($this->enemyPlayer, 1, 5);

        $this->enemyPlayer->createFigures([
            $this->enemyKing,
            $this->enemyBishop
        ]);

        $this->game->start();

    }


    function testVerify() {
        $enemies = $this->enemyPlayer->getFigures();
        $allies = $this->player->getFigures();

        for ($x = 7; $x >= 0; $x--) {
            for($y = 7; $y >= 0; $y--) {
                if(
                    ($x == 1 && $y == 0)
                    || ($x == 3 && $y == 0)
                    || ($x == 5 && $y == 0)
                    || ($x == 2 && $y == 1)
                    || ($x == 3 && $y == 1)
                    || ($x == 4 && $y == 1)
                    || ($x == 0 && $y == 2)
                    || ($x == 1 && $y == 2)
                    || ($x == 2 && $y == 2)
                    || ($x == 3 && $y == 2)
                    || ($x == 4 && $y == 2)
                    || ($x == 5 && $y == 2)
                    || ($x == 2 && $y == 3)
                    || ($x == 3 && $y == 3)
                    || ($x == 4 && $y == 3)
                    || ($x == 1 && $y == 4)
                    || ($x == 3 && $y == 4)
                    || ($x == 5 && $y == 4)
                    || ($x == 0 && $y == 5)
                    || ($x == 3 && $y == 5)
                    || ($x == 3 && $y == 6)
                    || ($x == 3 && $y == 7)
                ) {
                    $this->assertTrue($this->figure->verify($x, $y, $allies, $enemies), "Queen true: x: $x, y: $y");
                } else {
                    $this->assertFalse($this->figure->verify($x, $y, $allies, $enemies), "Queen false: x: $x, y: $y");
                }
            }
        }
    }

    function testCanSave()
    {
        $this->player->check($this->enemyBishop->getId());
        $this->assertTrue($this->figure->canSave($this->allyKing, $this->enemyBishop, $this->player->getFigures(), $this->enemyPlayer->getFigures()));
    }

    function testAttackKing()
    {
        $allies = $this->player->getFigures();
        $enemies = $this->enemyPlayer->getFigures();

        $this->assertTrue($this->figure->attackKing($this->enemyKing, $allies,  $enemies));
        $this->enemyKing->move(4, 7, $enemies, $allies);
        $this->assertFalse($this->figure->attackKing($this->enemyKing, $allies,  $enemies));
    }

    function tearDown()
    {
        $this->game->delete();
    }


}
